name: Python Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev pkg-config python3-dev libgirepository1.0-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest streamlit arabic-reshaper python-bidi groq supabase
          pip install pycairo xhtml2pdf

      - name: Test with pytest
        run: |
          python -m pytest test_app.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
